### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by christianloth** [killerdirt/TAMU-ClassRegistrationSnipe#1]
I'm getting an error that says:

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='submit' and @value='Submit']"}

**Comment by christianloth** [comment]
Great program though, I am a student at Texas A&M as well.

**Comment by killerdirt** [comment]
My apologies didn't get back to you until way too late but the error message isn't descriptive enough for me to debug it. Do you remember what screen/page the error is given on?
